// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xalapsmbxjiroltmkats.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhbGFwc21ieGppcm9sdG1rYXRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDIzOTksImV4cCI6MjA3NDQ3ODM5OX0.voTlcBbGhZ_oKllfSDxos-hco9jeUnsM3lQSZ6I3T2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});